Class Assignment: Create a NumPy array of 20 elements (from 1 to 20). Using slicing, extract:

The first 5 elements.
The elements from index 5 to 15.
The last 3 elements

In [ ]:
import numpy as np
arr=np.array(range(1,21))
print(arr)
print(arr[:5])
print(arr[5:16])
print(arr[-3:])

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[1 2 3 4 5]
[ 6  7  8  9 10 11 12 13 14 15 16]
[18 19 20]


Class Assignment: Create a NumPy array of 10 random integers. Use np.argsort() to get the indices that would sort the array in ascending order, then print the sorted array using these indices.

In [ ]:
import numpy as np
arr=np.random.randint(1,10,size=10)
print(f"Original Array :{arr}")
print(f"Argumental sort :{np.argsort(arr)}")

Original Array :[8 2 2 7 1 3 8 5 6 5]
Argumental sort :[4 1 2 5 7 9 8 3 0 6]


Class Assignment: Create a 1D NumPy array of 10 integers and randomly replace 2 elements with np.nan. Replace all NaN values in the array with the number 0.

In [ ]:
import numpy as np
arr=np.array(range(1,11),dtype=float)
print(f"Original Array :{arr}")
i=np.random.randint(0,10)
arr[i]=np.nan
j=np.random.randint(0,10)
arr[j]=np.nan
print(f"Modified Array :{arr}")
arr[np.isnan(arr)]=0
print(f"Replacing nan with 0 :{arr}")

Original Array :[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
Modified Array :[ 1.  2.  3.  4.  5. nan nan  8.  9. 10.]
Replacing nan with 0 :[ 1.  2.  3.  4.  5.  0.  0.  8.  9. 10.]
