2. Problem: Write a Python program that finds the GCD (Greatest Common Divisor) and LCM (Least Common Multiple) of all numbers in a given range [a, b] where a <= b

In [ ]:
import math

def gcd(a, b):
    if(a==0): return b
    return gcd(b%a,a)

def find_gcd_lcm_of_range(start, end):
    # current_gcd=gcd(start,end)
    # current_lcm=(start*end)//(current_gcd)
    # return current_gcd, current_lcm
    gcd_result=[]
    lcm_result=[]
    for i in range(start,end+1):
      for j in range(i+1,end+1):
        hcf=gcd(i,j)
        gcd_result.append({f"{i} and {j} ",hcf})
        lcm=(i*j)//hcf
        lcm_result.append({f"{i} and {j} ",lcm})

    return gcd_result,lcm_result


start = int(input("Enter the start number: "))
end = int(input("Enter the end number: "))
gcd_result, lcm_result = find_gcd_lcm_of_range(start, end)
print(f"The GCD of numbers between {start} and {end} is {gcd_result}")
print(f"The LCM of numbers between {start} and {end} is {lcm_result}")

Enter the start number: 1
Enter the end number: 2
The GCD of numbers between 1 and 2 is [{1, '1 and 2 '}]
The LCM of numbers between 1 and 2 is [{'1 and 2 ', 2}]


3. Problem: Write a Python program to solve the quadratic equation of the form ax^2 + bx + c = 0 for given a, b, and c. The program should return the two roots (if they exist) or a message if the equation has no real roots.

In [ ]:
import math

def solve_quadratic(a, b, c):
    discriminant = b**2 - 4 * a * c
    if discriminant > 0:
       #Implement your code here....
       root1=(-b + math.sqrt(discriminant))/(2*a)
       root2=(-b-math.sqrt(discriminant))/(2*a)
       return {root1,root2}

    elif discriminant == 0:
      roots= -b/(2*a)
      return {roots,roots}

    else:
        return "No real roots"


a, b, c = 1, -3, 2
result = solve_quadratic(a, b, c)
print(f"The roots are: {result}")

The roots are: {1.0, 2.0}


4. Problem: Write a Python program to generate all Pythagorean triplets (a, b, c) where a^2 + b^2 = c^2 for a <= b <= c <= n.


In [ ]:
def pythagorean_triplets(n):
    triplets = []
    for a in range(1, n + 1):
        for b in range(a, n + 1):
            for c in range(b, n + 1):
                if a**2 + b**2 == c**2:
                    triplets.append((a, b, c))
    return triplets


n = 20
triplets = pythagorean_triplets(n)
print(f"Pythagorean triplets up to {n}: {triplets}")

Pythagorean triplets up to 20: [(3, 4, 5), (5, 12, 13), (6, 8, 10), (8, 15, 17), (9, 12, 15), (12, 16, 20)]


6. Problem: Create a program that simulates a simple bank account system. The program should allow a user to perform the following operations:
a. Check balance
b. Deposit money
c. Withdraw money
d. Exit the program
Implement this system using loops to keep the program running until the user decides to exit.

In [ ]:
def bank_account_system():
    balance = 1000  # initial balance
    while True:
        print("\n--- Bank Account System ---")
        print("1. Check Balance")
        print("2. Deposit Money")
        print("3. Withdraw Money")
        print("4. Exit")
        choice = int(input("Enter your choice: "))

        if choice == 1:
           #Implement your code here....
           print(f"Your Current Balance is :{balance}\n")



        elif choice == 2:
           #Implement your code here....
           deposite=int(input("Enter the money to deposite :"))
           balance +=deposite
           print("Money Deposited !\n")



        elif choice == 3:
            #Implement your code here....
            withdraw=int(input("Enter the money to withdraw :"))

            if(balance-withdraw < 0) :
              print("Less balance !!\n")
            else :
              balance -=withdraw
              print("Money Withdrawn !\n")



        elif choice == 4:
            print("Exiting the system. Goodbye!")
            break
        else:
            print("Invalid choice. Please try again.")

bank_account_system()


--- Bank Account System ---
1. Check Balance
2. Deposit Money
3. Withdraw Money
4. Exit
Enter your choice: 1
Your Current Balance is :1000


--- Bank Account System ---
1. Check Balance
2. Deposit Money
3. Withdraw Money
4. Exit
Enter your choice: 2
Enter the money to deposite :2000
Money Deposited !


--- Bank Account System ---
1. Check Balance
2. Deposit Money
3. Withdraw Money
4. Exit
Enter your choice: 1
Your Current Balance is :3000


--- Bank Account System ---
1. Check Balance
2. Deposit Money
3. Withdraw Money
4. Exit
Enter your choice: 3
Enter the money to withdraw :1000
Money Withdrawn !


--- Bank Account System ---
1. Check Balance
2. Deposit Money
3. Withdraw Money
4. Exit
Enter your choice: 1
Your Current Balance is :2000


--- Bank Account System ---
1. Check Balance
2. Deposit Money
3. Withdraw Money
4. Exit
Enter your choice: 4
Exiting the system. Goodbye!


1. Problem: Find Longest Substring Without Repeating Characters


In [ ]:
def longest_substring(s):
    #Implement your code here....
    n = len(s)
    charSet = set()
    maxLen = 0
    l = 0

    for r in range(n):
        while s[r] in charSet:
            charSet.remove(s[l])
            l += 1
        charSet.add(s[r])
        maxLen = max(maxLen, r - l + 1)

    return maxLen


s = input("Enter a string: ")
print(f"The length of the longest substring without repeating characters is {longest_substring(s)}")

Enter a string: abcdab
The length of the longest substring without repeating characters is 4


1. Calculate the mean, median, mode, standard deviation, and variance for the dataset:
[5.0, 10.0, 15.0, 20.0, 25.0, 30.0, 35.0]

In [ ]:
import statistics as stats
dataset=[5,10,15,20,25,30.35]
mean=stats.mean(dataset)
median=stats.median(dataset)
mode=stats.mode(dataset)
std_dev=stats.stdev(dataset)
variance=stats.variance(dataset)
print(f"Mean : {mean}")
print(f"Median : {median}")
print(f"Mode : {mode}")
print(f"Standard Deviation : {std_dev}")
print(f"Variance : {variance}")

Mean : 17.558333333333334
Median : 17.5
Mode : 5
Standard Deviation : 9.448302316642216
Variance : 89.27041666666668


2. Generate a random data set of size 100 with values between 1 and 50. Calculate all the statistical measures discussed above.


In [ ]:
import statistics as stats
import random
dataset=[]
for i in range(100):
  dataset.append(random.randint(1,51))

mean=stats.mean(dataset)
median=stats.median(dataset)
mode=stats.mode(dataset)
std_dev=stats.stdev(dataset)
variance=stats.variance(dataset)

print(f"Mean : {mean}")
print(f"Median : {median}")
print(f"Mode : {mode}")
print(f"Standard Deviation : {std_dev}")
print(f"Variance : {variance}")



Mean : 25.1
Median : 26.0
Mode : 33
Standard Deviation : 14.577206505189858
Variance : 212.4949494949495


Create a 5x5 array filled with random integers from 0 to 10.

1.Create a 1D array of shape (5,) that will be added to each row of the 5x5 array using broadcasting.
2.Multiply each column of the 5x5 array by a 1D array of shape (5,) using broadcasting.

In [ ]:
import numpy as np
arr=np.random.randint(0,11,(5,5))
print(f"Random array \n:{arr}")
nums=np.random.randint(0,10,(5,))
print(f"Random 1D array \n:{nums}")

print(f"After adding :\n{arr+nums}")
print(f"After multiplying :\n{arr*nums}")



Random array 
:[[ 7  3  5  6  1]
 [ 0  5  6  0  6]
 [ 7  1  9  4 10]
 [ 9  8  5  2 10]
 [ 5 10  1  8 10]]
Random 1D array 
:[5 4 0 2 5]
After adding :
[[12  7  5  8  6]
 [ 5  9  6  2 11]
 [12  5  9  6 15]
 [14 12  5  4 15]
 [10 14  1 10 15]]
After multiplying :
[[35 12  0 12  5]
 [ 0 20  0  0 30]
 [35  4  0  8 50]
 [45 32  0  4 50]
 [25 40  0 16 50]]




Array Manipulation

    Create a 1D array with values from 1 to 20.
    Reshape the array into a 4x5 matrix.
    Flatten the reshaped matrix back into a 1D array.
    ind the mean, standard deviation, and sum of the reshaped matrix.



In [ ]:
arr=np.random.randint(1,20,(20,))
print(f"Random array \n:{arr}")
nums=arr.reshape(4,5)
print(f"Reshaped array \n:{nums}")
v=arr.flatten()
print(f"Flattened array \n:{v}")
print(f"Mean : {np.mean(nums)}")
print(f"Standard Deviation : {np.std(nums)}")
print(f"Sum : {np.sum(nums)}")

Random array 
:[13 10 16 18 10  2  2 12  6 16  7 17  8 19  4 15  7 13  6 19]
Reshaped array 
:[[13 10 16 18 10]
 [ 2  2 12  6 16]
 [ 7 17  8 19  4]
 [15  7 13  6 19]]
Flattened array 
:[13 10 16 18 10  2  2 12  6 16  7 17  8 19  4 15  7 13  6 19]
Mean : 11.0
Standard Deviation : 5.440588203494177
Sum : 220
